### ISSUE TITLE
TreeGrid expand problem

### ISSUE THREAD

**Issue by vlipovetskii** [mvysny/karibu-testing#68] opened 2021-03-26 14:44 UTC
Neither expand nor expandRecursively don't invoke lambda passed to addComponentColumn.

**Comment by mvysny** [comment] 2021-03-29 11:50
Hmm, that is true, the `expand()` nor `expandRecursively()` doesn't actually render the data being fetched, therefore the `ComponentRenderer` lambda is not invoked.

However, once you start asserting on the items displayed in the TreeGrid using Karibu-Testing (using `expectRow()`, `_dump()`, `_getFormatted()` or any of the grid-formatting test functions), the `ComponentRenderer` must definitely be invoked at that point. Therefore, the correct way to test the `ComponentRenderer`/`addComponentColumn()` is to assert on the displayed contents, using the functions above.

Please let me know whether this works for your use-case.

**Comment by mvysny** [comment] 2021-12-09 09:16
Closing as won't fix, please reopen if the issue is not fixed to your liking :+1:

**Closed by mvysny** 2021-12-09 09:16 UTC
Labels: question
