### ISSUE TITLE
Vaadin 14 (with polymere) grid testing

### ISSUE THREAD

**Issue by chrisw73** [mvysny/karibu-testing#38] opened 2020-06-05 05:44 UTC
Hi Martin! It's me again ;-). I am currently failing in two tasks:

1. I have a textfield with an attached ValueChangeListener filtereng the grid data in the grid-attached dataprovider. Now I want to know if the filter worked (it works in the running UI Application ;-)) but in my tests 2 things struck me as strange: 1st the filter code in my ValueChangeListener is never called. 2nd When I look up the items in the dataprovider they are not filtered...

Here is my filter code:
        filterTextField.addValueChangeListener(keyEvent -> {
            dataProvider.addFilter(ma ->
                StringUtils.containsIgnoreCase(ma.getName(), filterTextField.getValue()) ||
                StringUtils.containsIgnoreCase(ma.getSurname(), filterTextField.getValue()) 
            );
        });

2. In another grid I need to test I have one column with a NativeButtonRenderer - Is there any chance to invoke a click on this button on - letzt say - the first row of the grid? Hov to access the renderer of a specifiv cell in the grid anyways?

It would be nice, if we can sort these issues out, that they'll become part of a tutorial, for they may be pretty common ;-).

**Comment by mvysny** [comment] 2020-06-05 07:59
Hi Chris :)

1. That is very strange: the `ValueChangeListener` is invoked from a server-side Vaadin when changing a value of `TextField` (or any `HasValue` for that matter), and there are lots of tests in this regard also in Karibu-Testing. Could you please make sure that you're changing the value of the correct text field? Also maybe the debugger is acting up - could you add a couple of `println`s here and there?

2. You can use `GridKt._clickRenderer(0, "edit")` but you're right - I'll document it :)

I'm on a vacation right now so I'll answer any further questions next week :+1:

**Comment by chrisw73** [comment] 2020-06-05 11:23
2. Thanks! Works very well :-)

1. The ValueChangeListener works fine and is called, just the filter seems not to be applied to the rows in the grid or better: the data provider. The inner lambda is never being called. When I execute the same code in the UI the lambda is called for every row in the grid/data provider... Pretty strange to me... Lack in Karibu? ;-).

Nice vacation to you!

**Comment by mvysny** [comment] 2020-06-08 05:52
Ah, right! Another piece of documentation missing. I'll fix that right away :)

The gist of the problem is as follows: when the Vaadin app is running with the full client-side code, then the `dataProvider.addFilter()` probably calls `dataProvider.refreshAll()` at some point. That call informs the client-side Grid code that it needs to throw away all data and ask for a fresh data.

With Karibu-Testing there is no client-side, therefore `dataProvider.refreshAll()` does nothing since there is no client-side that can re-fetch the data.

However, the filters do get called: they are invoked every time you call one of Karibu-Testing's `GridKt` methods such as `expectRows()` or `expectRow()` or `_clickRenderer()`, or one of the "lower-level" functions `_get(0)` or `_size()` or `_getFormattedRow()`.

The reasoning is that in this particular case the unit-test itself can "play the role of the client-side": after the filter has been modified, the most reasonable thing for the test to do is to assert on the rows of the Grid, which will in turn invoke the filters themselves.

Please let me know whether this sounds reasonable, and if yes, I'll update the documentation with this information.

**Comment by chrisw73** [comment] 2020-06-08 08:47
GridKT._size(myGrid) did the trick. Thanks a lot again. 
Regarding the documentation: IMHO it is quite confusing to have examples in Kotlin, Grooviy and Java in one page. I know it is much more work, but did you think of having 3 seperate pages?

**Comment by mvysny** [comment] 2020-06-08 10:01
> IMHO it is quite confusing to have examples in Kotlin, Grooviy and Java in one page.

I'm sorry to hear that. Unfortunately keeping those 3 separate pages in sync would create a lot of maintenance work when the documentation is updated... The ideal solution would be to have a tabbed examples with the "Java" / "Kotlin" / "Groovy" tabs, but GitHub doesn't support those unfortunately.

> BTW Grid Testing could be an own chapter in "The Book of Karibu" ;-)

Haha, definitely :-p Thanks for a great tip on the name of the book!

**Comment by mvysny** [comment] 2020-06-08 10:02
Could you please review the README now, whether it answers your questions? Please feel free to add any suggestions as PRs :+1:

**Comment by chrisw73** [comment] 2020-06-08 10:28
Regarding the maintanance work: Completely agreed... I assume there is no tabbing implemented in markdown ;-).

I reviewed the Readme.md and looks fine now. I hope I would have found it, If I where on the search for that info... In fact now I know where to look :-D.

**Comment by mvysny** [comment] 2020-06-08 10:36
> I assume there is no tabbing implemented in markdown ;-).

Yeah, I can't find any info on this either, I assume it's not supported yet.

> I hope I would have found it, If I where on the search for that info... 

Ah, I just wrote that chapter, so you couldn't discover that documentation yesterday. The documentation is ever improving - please if you have any questions or feedback with respect to the documentation just let me know and I'll try to explain in additional chapter.

> In fact now I know where to look :-D.

Sounds good! Hopefully Google will also index the page again and so everybody should be able to find this info much easier.

With your permission I'm closing the issue as fixed, but please feel free to file new bugs if there's docs missing or a feature missing.

**Closed by mvysny** 2020-06-08 10:36 UTC
Labels: bug, question

**Comment by mvysny** [comment] 2020-06-08 11:16
Regarding the tabbing implementation in GitHub markdown: I found this one: https://github.com/github/markup/issues/435 but probably that wasn't a correct place? I'll try to file another bug report at https://github.com/gjtorikian/commonmarker/issues perhaps that's more appropriate place...
