### ISSUE TITLE
Running on JDK12 results in NoSuchFieldException: modifiers

### ISSUE THREAD

**Issue by vaadin-miki** [mvysny/karibu-testing#31] opened 2020-04-07 20:04 UTC
It seems that `UtilsKt.makeNotFinal` is no longer possible in Java 12.

Downgrading to Java 10 (and probably 11) helps, but it would be nice if there is a workaround for the latest version.

**Comment by mvysny** [comment] 2020-04-08 05:12
Hi, thanks for letting me know! The issue is known for Java 13 and unfortunately there's not much we can do apart from downgrading to Java 11 or using Vaadin 15. Please see #29 for more details.

That being said, I will improve the error message for Java 12 to include this piece of information.

**Comment by mvysny** [comment] 2020-04-08 05:41
Fixed in Karibu-Testing 1.1.24

**Closed by mvysny** 2020-04-08 05:41 UTC
Labels: bug
