### ISSUE TITLE
Only register MockRouteNotFoundError if no other error view is detected

### ISSUE THREAD

**Issue by jstueckrath** [mvysny/karibu-testing#50] opened 2020-10-09 08:32 UTC
Recently I upgraded to Vaadin 14.4.0 and Karibu 1.2.5 (from Vaadin 14.2.x and Karibu 1.1.x). After all expected changes I ran into the following Exception when executing tests:
```
com.vaadin.flow.server.InvalidRouteLayoutConfigurationException: Only one target for an exception should be defined. Found <MyErrorViewName> and 'com.github.mvysny.kaributesting.v10.MockRouteNotFoundError' for exception 'com.vaadin.flow.router.NotFoundException'
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.handleRegisteredExceptionType(AbstractRouteRegistry.java:428)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.addErrorTarget(AbstractRouteRegistry.java:394)
	at com.vaadin.flow.server.startup.ApplicationRouteRegistry.lambda$setErrorNavigationTargets$3(ApplicationRouteRegistry.java:307)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at com.vaadin.flow.server.startup.ApplicationRouteRegistry.setErrorNavigationTargets(ApplicationRouteRegistry.java:307)
	at com.github.mvysny.kaributesting.v10.Routes.register(Routes.kt:47)
	at com.github.mvysny.kaributesting.v10.spring.MockSpringServlet.createServletService(MockSpringServlet.java:47)
	at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:185)
	at com.vaadin.flow.server.VaadinServlet.init(VaadinServlet.java:72)
	at com.github.mvysny.kaributesting.v10.MockVaadin.setup(MockVaadin.kt:151)
	...
```
The problem seems to be that both the application and the Karibu Mock register a custom `NotFoundException`. I avoided this problem by removing the `MockRouteNotFoundError` after views have been detected.
```
allRoutes = new Routes().autoDiscoverViews("...");
allRoutes.getErrorRoutes().remove(MockRouteNotFoundError.class);
```
Is it possible to change `autoDiscoverViews(...)` such that it only registers the `MockRouteNotFoundError` if no other error view is already registered?

P.S.: I am using `karibu-testing-v10-spring` and set up the tests as it was done in the corresponding TShirt Example.

**Comment by mvysny** [comment] 2020-10-09 09:38
The purpose of `MockRouteNotFoundError` is for Karibu-Testing to fail eagerly with an informative exception if there is no such route. However you're right that it gets in the way of app-specific `NotFoundException` handlers.

One solution would be to auto-remove the `MockRouteNotFoundError` class from `Routes.errorRoutes` when the app introduces its own specific `NotFoundException` handler, exactly as you suggest. However, I think what makes most sense is to generally test the app with eagerly-failing `MockRouteNotFoundError` class, and only use `MyErrorViewName` when writing tests specific for `MyErrorViewName`.

The problem is as follows: imagine that you navigate to a non-existing route. Instead of failing eagerly with an informative exception, the navigation will succeed instead, and the test will fail later on when you try to look up a component from the page. At that point you will see the `MyErrorViewName` class in the component tree dump and realize that it was a navigation to a non-existing route. However, it requires much more brain power than simply having an informative error message.

My counter-proposal would actually be for Karibu-Testing to auto-ignore `MyErrorViewName`; however the route-not-found exception message will be modified to mention this fact and will instruct you on how to register `MyErrorViewName` and remove the `MockRouteNotFoundError`. However, I'd love to hear your thoughts on this first.

**Comment by jstueckrath** [comment] 2020-10-09 15:13
I see, so the `MockRouteNotFoundError` will cause a test to fail at the moment of navigation instead of silently navigating to an error view, which has to be detected e.g. via the Locator. 

I think there is no "right" way here since the preferred way seems to depend of ones "philosophy". If an app does not require special error handling, one is probably not interested in testing navigation errors and will be grateful when a test fails fast due to such an error. On the other hand, if you consider the displaying of error pages to be important behaviour of the app, you want to test it as well. In that case a navigation error should not fail a test since it may in fact be the expected behaviour.

In my case I defined an error view that is used when a page does not exist, but also wenn a page exists but the current user has insufficient rights to access it (thus not revealing that there is a page he can not access). I also wrote tests that check that the custom error view is displayed in those cases.

All in all I prefer my original suggestion since the mocked error handling is closer to the actual behavour of the app. Maybe the best way is to assume that `MockRouteNotFoundError` is wanted if no custom error view is defined. There is also the option to introduce a parameter to the `autoDiscoverViews(...)` method to control whether an existing error view or the `MockRouteNotFoundError` should take precedence if both exist. Maybe the `autoDetectErrorRoutes` flag could be expanded to a modes enum with values such as "no detection", "prefer original view" and "prefer mock views". However, I am not sure whether I understood the flag correctly. The documentation says `if false then [HasErrorParameter] error views are not auto-detected. This emulates the old behavior of this method`, but in version 1.1.23 my custom error view was auto-detected by that method (I wrote test checking for it).

**Comment by mvysny** [comment] 2020-10-12 09:06
> I also wrote tests that check that the custom error view is displayed in those cases.

Exactly my point: you only need your own custom error message when testing the error behavior; in all other cases it's handy when a test fails fast.

That being said:

* Karibu can't really differentiate between these two test scenarios, and therefore it shouldn't set its own policy here, damaging the entire testing experience;
* trying to be helpful only leads to `InvalidRouteLayoutConfigurationException`;
* moreover the dev expects his own error page to be shown, while failing with `MockRouteNotFoundError` is perceived confusing. 

I agree I need to do something about this. Possible solutions:

* Only use `MockRouteNotFoundError` when no other error handler is detected (as you suggest)
* Another would be for all lookup methods to detect that the current route is a `HasErrorParameter<NotFoundException>` and fail cleanly; however that would prevent the testing of the error page itself.
* Another would be to hook into `UI.getCurrent().navigate()` and fail cleanly in case of `HasErrorParameter<NotFoundException>`, however that still prevent the testing of the error page itself.

Since I can't see a perfect solution here, I'll do as you suggest and only auto-install `MockRouteNotFoundError` if there is no `HasErrorParameter<NotFoundException>`.

>  The documentation says if false then [HasErrorParameter] error views are not auto-detected. This emulates the old behavior of this method, but in version 1.1.23 my custom error view was auto-detected by that method (I wrote test checking for it).

Sounds like a bug in handling of the `autoDetectErrorRoutes` parameter; however I'll remove the parameter anyways since it's much simpler to simply clear the `Routes.errorRoutes` set after the detection.

**Comment by mvysny** [comment] 2020-10-12 09:14
The `autoDetectErrorRoutes` parameter removed in 2716e759aad9f638e895fd8213aa0c91a835e4fa

**Comment by mvysny** [comment] 2020-10-12 10:21
Fixed in Karibu-Testing 1.2.6

**Closed** 2020-10-12 10:21 UTC
Labels: bug

**Comment by mvysny** [comment] 2020-10-12 10:30
>  Maybe the autoDetectErrorRoutes flag could be expanded to a modes enum with values such as "no detection", "prefer original view" and "prefer mock views".

Let's not have a configuration for something that can easily be done with a bit of code :+1:

**Comment by jstueckrath** [comment] 2020-10-12 10:56
> Since I can't see a perfect solution here, I'll do as you suggest [...]

I also did not see a perfect solution but I think this one handles most case good enough. I think it would not be a good solution to prevent testing of the error pages itself.

> Sounds like a bug in handling of the autoDetectErrorRoutes parameter [...]

Well, to me it felt like a feature. :smile:

> Let's not have a configuration for something that can easily be done with a bit of code 👍

I agree, especially with the `autoDetectErrorRoutes` parameter removed, such a configuration would not add enough value.

Anyway, thank you for the fix. 👍
